### ISSUE TITLE
How to perform a proper MySQL export

### ISSUE THREAD

**Issue by happykeppi** [pellcorp/opendb#75]
First, I am still using the original 1.5.0.7 release, which I have recently modified to make it work with PHP 5.6. In this context I also tried to move from MySQL 4.1.22 to 5.6.19. However, all my attempts eventually failed. Both the original as well as the modified version are working fine with the MySQL4 database. However, if I am going to export everything and import it into a MySQL5 database, the listings always say "No match found".
Can you please tell me a proper way how to export the whole data and import it into a new database?

**Comment by pellcorp** [comment]
The export / import process built into OpenDB is not designed for this purpose.  You should instead look at using phpMyAdmin.

The export syntax between mysql 4 and 5 is quite different.

There is a alternative release version of 1.5.0.7 which has mysql 5 support which may also be of help

https://github.com/pellcorp/opendb/tree/RELEASE_1_5_0_7_MSQL55

**Comment by happykeppi** [comment]
Hello Jason, thank you for your response. I actually did a mysqldump on the command line to export and import the database. But I will also try to use phpmyadmin for a change.

I also used the above mentioned version with MySQL 5.5 support once, but it also showed "No match found" at the end. But I guess the database got corrupted somehow during the initial export process.

**Comment by pellcorp** [comment]
phpmyadmin will complain if it does not understand anything in the SQL, so I find it a good option for export / import kinds of operations with opendb.

**Comment by happykeppi** [comment]
I just tried the export and import via phpmyadmin and it led to the same result (2,4 MB after export; 2,8 MB after import). Although the number of entries is absolutely identical, all items are gone in the front end and I see nothing but "No match found". I have no clue how to fix that. In the worst case I will stick to the existing MySQL4 database. Thank you for your help anyway!

**Comment by pellcorp** [comment]
feel free to send me your export and I will see what is going on.  Its surely something simple.

A screenshot of your "No match found" screen in listings.php would be good too.

You can send it to jason at pellcorp dot com

**Comment by pellcorp** [comment]
Hi,

Opendb was producing invalid SQL in your case because you had a field named 'release' which is a reserved word in mysql 5.5

I have updated both master and the RELEASE_1_5_0_7_MYSQL55 branch with a fix for both the AS column name and ORDER BY column name sql.

**Comment by happykeppi** [comment]
I'm glad you have found the problem. What am I supposed to do now? Trying the recently modified/updated version with yesterday's dump?

**Comment by pellcorp** [comment]
Correct either th 1.6 beta (master) or the mysql55 1.5.0.7 branch

**Comment by happykeppi** [comment]
Okay, I will try that and give you a feedback asap!

**Comment by happykeppi** [comment]
Thank you for all your help. The problem has been solved due to your fixes! :+1:
