### ISSUE TITLE
Site plugin The Movie Database update

### ISSUE THREAD

**Issue by robboor** [pellcorp/opendb#76]
The TMDB plugin has a small coding error
Line 93
        $jsonData = json_decode($this->fetchURI($this->baseURL . 'movie/' . $search_attributes_r['tmdb_id'] . '?api_key=' . $this->apikey . '&append_to_response=casts', true), true);

should read

        $jsonData = json_decode($this->fetchURI($this->baseURL . 'movie/' . $search_attributes_r['tmdb_id'] . '?api_key=' . $this->apikey . '&append_to_response=casts'), true);

Thx,
Rob Boor

**Comment by pellcorp** [comment]
Can you create a pr for this. Makes it far easier to apply the fix

**Comment by robboor** [comment]
I'm a first user of GitHub, so I don't exactly know how to create a pr, sorry about that.

**Comment by robboor** [comment]
Closed by mistake

**Comment by pellcorp** [comment]
1) Fork the repository
2) Clone your local fork to your PC
3) Create a separate branch
4) Make your change
5) Push your change to your fork
6) Back in browser github will prompt you to create a PR

https://help.github.com/articles/using-pull-requests/

**Comment by pellcorp** [comment]
cLOSING
