### ISSUE TITLE
Import Items does not work

### ISSUE THREAD

**Issue by daylabourer** [pellcorp/opendb#77]
Hello Jason!

I am a new opendb user and I have some problem with importing items. I tried to find a solution but I'm failed. I need your help, please!

So, when I wanted to importing items from the main menu I chose a csv file, or opendb xml file. I followed the process: choose file button - submit - match fields - import items button. Trial run was/was'nt checked. Everything looked good, but nothing was imported.
I tried this on the demo site with the same result.

My configuration:
os: windows 7
xampp: 5.6.8
MySQL: 5.6.24
php: 5.6.8
opendb: 1.6.0

Here is the content of the CSV file:
Title,Year
Werewolf The Beast Among Us,2012
Bad Ass,2012
The Tourist,2010

In the log it looks like the import file (csv for instance) processed corretly anyway.

Please help me if you can!

Thank You!

---
INFO	admin	::1	20/07/15 14:30:06	lib/importcache.php	import_cache_insert	 	(?)
INFO	admin	::1	20/07/15 14:30:06	lib/importcache.php	import_cache_update_cachefile	 	(?)
INFO	admin	::1	20/07/15 14:30:14	lib/importcache.php	import_cache_delete	Deleted import_cache record	(?)
INFO	admin	::1	20/07/15 14:30:14	lib/fileutils.php	delete_file	 	(?)
 	 	 

---

![clipboard-1](https://cloud.githubusercontent.com/assets/13417155/8775686/dbc7825c-2eea-11e5-864f-3137cefde8a9.jpg)
![clipboard-2](https://cloud.githubusercontent.com/assets/13417155/8775688/dbcc3a68-2eea-11e5-88c4-87f98e607774.jpg)
![clipboard-3](https://cloud.githubusercontent.com/assets/13417155/8775689/dbcc87c0-2eea-11e5-9775-987284bea382.jpg)
![clipboard-4](https://cloud.githubusercontent.com/assets/13417155/8775687/dbca1c6a-2eea-11e5-81be-7edda3fbdd68.jpg)

**Comment by pellcorp** [comment]
Can you try this on the demo site please.

**Comment by pellcorp** [comment]
never mind, I can see the same result on the demo site.

**Comment by ddddenis** [comment]
Same here with a fresh RELEASE_1_6_1

**Comment by pellcorp** [comment]
There is a bug in the call to handle_item_insert

Really wish we had a decent set of regression tests

**Comment by pellcorp** [comment]
fixed in 1.6.2 

https://github.com/pellcorp/opendb/releases/tag/RELEASE_1_6_2
