### ISSUE TITLE
Sorting does not work in 1.6.0

### ISSUE THREAD

**Issue by MartinWunderli** [pellcorp/opendb#79]
I try to sort by item id. As you can see, in 1.0.5 sort was ok, in 1.6.0 it does not sort.

In 1.0.5: ![sorting-1 0 5](https://cloud.githubusercontent.com/assets/14999963/10388759/f1f817d2-6e6c-11e5-86bf-e547e12d2cd0.PNG) 

In 1.6.0: ![sorting-1 6 0](https://cloud.githubusercontent.com/assets/14999963/10388761/f6e67856-6e6c-11e5-9067-c42aa4272ce3.PNG)

Sorting by title however works fine.

**Comment by pellcorp** [comment]
Please try latest master, I believe I have the problem resolved

**Comment by MartinWunderli** [comment]
Yepp, works fine. And this strange first column disappeared too... ;-) Thanks.
