### ISSUE TITLE
Questions about OpenDb

### ISSUE THREAD

**Issue by wdrt-radio** [pellcorp/opendb#83]
Hi,

I work at a community radio station and we are looking for a searchable database for our music library (Records, CDs, Mp3s). Before I spend too much time diving into OpenDb, I was wondering if someone could tell me that what we want to do is feasible w/OpenDb.

Basically, I want someone to be able to enter a genre or song title. 

Any information would be greatly appreciated. 

Thanks!

Terry

**Comment by pellcorp** [comment]
It should work just fine, but there might be better alternatives targeted specifically at cataloguing music, OpenDb is quite generic, so some things won't be as specifically targeted to a music db as you might like.

The ability to search a track to get a title to be returned should work, if you use advanced search, but it won't work from the simple search box, as that just searches title field.
