### ISSUE TITLE
User-defined sortable column?

### ISSUE THREAD

**Issue by Paulo--M--** [pellcorp/opendb#85]
Hello,
In 'listings.php' was wondering whether it is possible to render a specific column "sortable" just like, for example, 'Title' and 'Owner' can be clicked to generate a new sort order.
Also, still in the 'listings' page, is it possible to add a specific column? I was specifically thinking of the IMDB Rating value, but I was wondering whether the "listing view" could in any way be configurable.
Many thanks in advance.

**Comment by pellcorp** [comment]
Both of these are already available.  Check out the Item Listing Configuration tool in Admin tools.

**Comment by Paulo--M--** [comment]
Apologies for having missed that. I have now dug around and found the feature. Is there a 'user manual' somewhere? Many thanks again.

**Comment by pellcorp** [comment]
There is only an incomplete wiki unfortunately.  Documentation was never my strong suit.  Feel free to ask questions here in the issues list and I will answer them.  If you feel like contributing back, contribute some additions to the wiki.  I believe you can do that from the github web site, but I have never tried.
