### ISSUE TITLE
Upgrading from OpenDb 1.5.0.4?

### ISSUE THREAD

**Issue by bitwrench** [pellcorp/opendb#86]
I have an OpenDb 1.5.0.4 install that is throwing the following errors:

Deprecated: Assigning the return value of new by reference is deprecated in /home/webgizmo/webwidget.net/media/functions/theme.php on line 423

Deprecated: Assigning the return value of new by reference is deprecated in /home/webgizmo/webwidget.net/media/functions/site_plugin.php on line 127

Deprecated: Assigning the return value of new by reference is deprecated in /home/webgizmo/webwidget.net/media/functions/filecache.php on line 758

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/webgizmo/webwidget.net/media/functions/theme.php:423) in /home/webgizmo/webwidget.net/media/include/begin.inc.php on line 142

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/webgizmo/webwidget.net/media/functions/theme.php:423) in /home/webgizmo/webwidget.net/media/include/begin.inc.php on line 142

Warning: Cannot modify header information - headers already sent by (output started at /home/webgizmo/webwidget.net/media/functions/theme.php:423) in /home/webgizmo/webwidget.net/media/functions/http.php on line 73

It looks like the current version is 1.6?

I had about 377 entries in the old install, and would just as soon avoid starting from scratch.

Is an upgrade possible?  Are there instructions for this posted somewhere?

Thanks for any and all help.

**Comment by pellcorp** [comment]
Hi,

The latest release is 1.6.2, 

https://github.com/pellcorp/opendb/releases/tag/RELEASE_1_6_2

https://github.com/pellcorp/opendb/wiki/Installation

**Comment by bitwrench** [comment]
Hi, Jason.

Thanks for the reply.

Hmmmm.  Well, I deleted the previous directory on the server, and then filled it with the new files.

The installer asked me for info about the database, I entered it, and it went through various checks and upgrades, apparently successfully.

However, when all was said and done, the installation does not recognize my admin or user passwords.

Any suggestions?

Thanks for the all the work you've put into this software!

**Comment by pellcorp** [comment]
Not sure, please check that the database does have the users you expect by going directly to the database using phpmyadmin or equivalent.

**Comment by bitwrench** [comment]
I used phpmyadmin to export the users, they are as expected.

Then, I used the Forgot Password function to have the installation send me a new password for a user.

I got the new password via email, and entered this new password into the login.

Got this message:

"You will be redirected to welcome page once you have successfully logged in"

Nothing further happened.

Tried this with both admin user, and owner user, both failed in this same way.

Thanks for your help.

**Comment by pellcorp** [comment]
Please check the opendb log file, and also the apache errors log

I have not seen this before

What environment are you running on (What OS, What php version, what apache version, what mysql version, etc)

**Comment by bitwrench** [comment]
The install is on a shared account at Dreamhost, which used to be Debian, but now I think is Ubuntu.

PHP 5.5.26

Dreamhost Apache 2.2.31-2

MySQL 5.6.25-log Protocol 10 Charset: UTF-8 Unicode (utf8)

I'm probably not smart enough to know what to look for in the logs, but I did find them.

Thanks.

**Comment by pellcorp** [comment]
The apache / php error log is most likely going to provide the reason why it failed, so without that I can't help.

**Comment by bitwrench** [comment]
AFAIK, there is not a separate PHP log available to DreamHost users.

This is the Apache error log, I think:

[Thu Dec 10 01:32:09 2015] [error] [client 62.210.152.89] File does not exist: /webwidget.net/wp
[Thu Dec 10 01:32:09 2015] [error] [client 62.210.152.89] File does not exist: /webwidget.net/missing.html
[Thu Dec 10 01:32:10 2015] [error] [client 62.210.152.89] File does not exist: /webwidget.net/wp
[Thu Dec 10 01:32:10 2015] [error] [client 62.210.152.89] File does not exist: /webwidget.net/missing.html
[Thu Dec 10 16:24:49 2015] [error] [client 52.35.180.31] File does not exist: /webwidget.net/missing.html
[Thu Dec 10 16:59:17 2015] [error] [client 75.183.40.190] File does not exist: webwidget.net/media/javascript/jquery-2.0.3.min.map, referer: http://webwidget.net/media/install.php
[Thu Dec 10 16:59:17 2015] [error] [client 75.183.40.190] File does not exist: /home/webgizmo/webwidget.net/missing.html, referer: http://webwidget.net/media/install.php

**Comment by pellcorp** [comment]
Nothing looks like a cause of the issue.  Can you send me login details to jason at pellcorp dot com and I can take a look directly.  Don't post them to this issue, send to my email directly please.

**Comment by pellcorp** [comment]
I suspect it might be an issue with the file based session management.  I have seen this before in shared hosting environments.  Its unclear to me why the logs are not showing it.

Can you change the include/local.config.php to enable session handling.  This will move session handling to the database.

$CONFIG_VARS['session_handler']['enable'] = TRUE;

**Comment by pellcorp** [comment]
If that does not work, if you can provide me with a temporary login to your server I can see if I can diagnose the issue that way.  I understand if you can't but I am not sure what else to suggest if moving session handling does not work.

Was there anything in the opendb logs/usagelog.txt

**Comment by bitwrench** [comment]
Installing 1.5.0.9 (last version without "remember me" functionality) seems to have done the trick.

Thanks for all your help!
