### ISSUE TITLE
Additional code for UTF-8 compatibility

### ISSUE THREAD

**Issue by happykeppi** [pellcorp/opendb#88]
I have a problem with the UTF-8 encoding after a security update of PHP by my web hosting company and believe the reason is the database connection, which is still running with latin1. While I am still waiting for a statement by the company's support, I found a solution to bring back the correct output in the web browser by adding the following lines after the DB connect in each php script I am using:

$mysql->query("SET character_set_connection = utf8");
$mysql->query("SET character_set_client = utf8");
$mysql->query("SET character_set_results = utf8");
$mysql->query("SET NAMES utf8");
mb_internal_encoding('UTF-8');

Where would be the best place to add this in opendb?

**Comment by pellcorp** [comment]
lib/database/mysql.inc.php and lib/database/mysqli.inc.php

**Comment by pellcorp** [comment]
Looks like it might already be there, you need to set the charset in the include/local.config.php, refer to 
https://github.com/pellcorp/opendb/pull/84

**Comment by happykeppi** [comment]
Thank you for your reply and your efforts. I'm afraid I didn't have this update yet. I will take a look at it, make the neccessary changes and test it later!

**Comment by pellcorp** [comment]
Assuming i can close
